version: 1.0.{build}
configuration: Release
image: Visual Studio 2022
dotnet_csp_version: 10.0.x
pull_requests:
  do_not_increment_build_number: true

install:
- ps: dotnet --version

build_script:
- ps: .\build.ps1 -experimental

test: off